### ISSUE TITLE
can't update

### ISSUE THREAD

**Issue by chudman85** [homebridge-panasonic-ac-platform/homebridge-panasonic-ac-platform#110]
USER: daviesserver
DIR: /usr/local
CMD: npm install -g homebridge-panasonic-ac-platform@1.8.3

npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path /usr/local/lib/node_modules/homebridge-panasonic-ac-platform
npm ERR! dest /usr/local/lib/node_modules/.homebridge-panasonic-ac-platform-UsR9GogQ
npm ERR! errno -66
npm ERR! ENOTEMPTY: directory not empty, rename '/usr/local/lib/node_modules/homebridge-panasonic-ac-platform' -> '/usr/local/lib/node_modules/.homebridge-panasonic-ac-platform-UsR9GogQ'

npm ERR! A complete log of this run can be found in: /Users/daviesserver/.npm/_logs/2023-12-14T17_11_19_658Z-debug-0.log

Operation failed. Please review log for details.

Any ideas on how to fix ????

**Comment by jandersonhill** [comment]
@embee8 Sorry to bother you, but we're getting errors with publishing to npm. The workflow within Github returns the following:

npm notice Publishing to https://registry.npmjs.org/ with tag latest and default access
npm ERR! code E404
npm ERR! 404 Not Found - PUT https://registry.npmjs.org/homebridge-panasonic-ac-platform - Not found
npm ERR! 404 
npm ERR! 404  'homebridge-panasonic-ac-platform@1.8.4' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

Any ideas on what I'm doing wrong?

**Comment by mkz212** [comment]
@chudman85 There are currently some problems. Version 1.8.4 will be coming out soon to solve the login problem. Be patient.

**Comment by embee8** [comment]
@jandersonhill, try replacing the npm token in the repository settings. That should fix it.

**Comment by jandersonhill** [comment]
@embee8 I created an npm token and added it to my GitHub secrets for this repo, but I'm still getting the same error. Is this down to inexperience of these tools, or could it be bombing as a result of the workflow being run once before with the same version number (as one would expect, Github updated to the latest version, but npm did not)?

**Comment by embee8** [comment]
You need to update it [here](https://github.com/homebridge-panasonic-ac-platform/homebridge-panasonic-ac-platform/settings/secrets/actions).

**Comment by jandersonhill** [comment]
Thank you :-)

**Comment by jandersonhill** [comment]
@embee8 Much appreciated, it now works as expected :-) On a slightly different topic, I seem to recall a short summary of the release notes was an option within the workflow when publishing to npm. Was this option removed?

**Comment by mkz212** [comment]
Version 1.8.4 released! If this solves the problem, please close the Issue.

**Comment by chudman85** [comment]
Manually deleted plugin folder and reinstalled corrected issue still wasn't able to update with new version posted until deleted folder.

**Comment by embee8** [comment]
> I seem to recall a short summary of the release notes was an option within the workflow when publishing to npm. Was this option removed?

In the past, one manually created a GitHub release which triggered the publishing workflow. Now, it's the other way around – running the workflow creates the release automatically. You can still edit the auto-generated release notes via the [release page](https://github.com/homebridge-panasonic-ac-platform/homebridge-panasonic-ac-platform/releases) to make it more readable and descriptive.

If you look at the recent release notes, you will see the reason why I have been trying to get contributors to write meaningful commit messages – unfortunately without success so far.

**Comment by mkz212** [comment]
> > I seem to recall a short summary of the release notes was an option within the workflow when publishing to npm. Was this option removed?
> 
> In the past, one manually created a GitHub release which triggered the publishing workflow. Now, it's the other way around – running the workflow creates the release automatically. You can still edit the auto-generated release notes via the [release page](https://github.com/homebridge-panasonic-ac-platform/homebridge-panasonic-ac-platform/releases) to make it more readable and descriptive.
> 
> If you look at the recent release notes, you will see the reason why I have been trying to get contributors to write meaningful commit messages – unfortunately without success so far.

Is it possible to make a window pop up after starting the workflow with fields where you give changelog and version? Or even chose publish as stable or beta (so it will be one workflow then)?

**Comment by jandersonhill** [comment]
> You can still edit the auto-generated release notes via the [release page](https://github.com/homebridge-panasonic-ac-platform/homebridge-panasonic-ac-platform/releases) to make it more readable and descriptive

Agreed

> I have been trying to get contributors to write meaningful commit messages – unfortunately without success so far

I think we'll get there :-) I think this last change from Panasonic caught everyone out and there was a mad scramble to figure out what was going on and how to fix it.

My fear is that this simply becomes a game of cat and mouse which is why I think we should try and minimise the number calls to their API to get status updates.

**Comment by mkz212** [comment]
> > You can still edit the auto-generated release notes via the [release page](https://github.com/homebridge-panasonic-ac-platform/homebridge-panasonic-ac-platform/releases) to make it more readable and descriptive
> 
> Agreed
> 
> > I have been trying to get contributors to write meaningful commit messages – unfortunately without success so far
> 
> I think we'll get there :-) I think this last change from Panasonic caught everyone out and there was a mad scramble to figure out what was going on and how to fix it.
> 
> My fear is that this simply becomes a game of cat and mouse which is why I think we should try and minimise the number calls to their API to get status updates.

Imagine such a situation. Their API is supposed to support their application. How many times a day does someone launch their application? I assume that the real desperation does it max 3 times a day. But even if someone would open 10 times a day every day, we have 10. And now the plugins (this and all the others) - they ask (which I checked) every 10 to 60 seconds - this gives us 8640 to 1440 inquiries. It's a completely different league.

**Comment by jandersonhill** [comment]
We have seven indoor units and I would imagine we use the app an average six times a day for each unit. We perhaps change two or three settings each time, still less than 100 to 150 API calls.

If we were to say that a ten-minute interval was reasonable for Homebridge to update (unless changing a setting via Homebridge), that would reduce the number of API calls to 175 plus maybe 50 to 100. Some might complain that it is inconvenient not to have the status update immediately if someone uses the IR remote, however I would argue that is less inconvenient than not having Homebridge available full stop!

If Panasonic really put the effort in to block 3rd-party add-ons, I have no doubt they will be able to do so.

**Comment by mkz212** [comment]
In the settings, I added the option to select refresh interval, from 10 seconds to 300 seconds (5 minutes). Default value is 30 s. Of course we can change the maximum value. What do you suggest? 10 minutes? 30 minutes?

However, I don't think there is a problem in this because as I say - most plugs have a refresh every 10 seconds.

**Comment by embee8** [comment]
At the moment, device updates are fetched in fixed – but configurable – intervals. An alternative approach is to fetch the device status when Apple Home requests an update, and then cache that result for some time and re-use it to the extent it doesn't make the app unusable. Based on how conservative Apple Home is with those requests, and how long the device state is cached, it could lighten the load by quite a bit.

---

> Is it possible to make a window pop up after starting the workflow with fields where you give changelog and version? Or even chose publish as stable or beta (so it will be one workflow then)?

Yes, to some extent, through [workflow inputs](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_dispatchinputs). But here are a few reasons why I am not a proponent of this idea:

- The text field for `string` inputs is single-line. Most likely too small to use it productively for release notes.
- A dropdown for beta/production is possible, but it would lead to a more complicated workflow file (branched logic) and it's easier to make an error in the dropdown compared to choosing and running the wrong workflow (which takes a few more clicks and gives a chance to spot errors along the way).
- Setting the version number in that step is not a very safe practice. A small typo could lead to a wrong tag and release, confusing users and requiring manual clean-up work. The better practice is to do this version-controlled, with a better handle on quality.
- Summarised, you'd trade two smaller workflows which are easier to maintain with a bigger one which is more complex and has the drawbacks listed above.

PS: This thread has gone off-topic. Probably best to continue in a separate issue if required.

**Comment by jandersonhill** [comment]
@mkz212 My feeling is the default could be five minutes, but we document it - and the reasons for it. Hopefully, other plugins will follow (or could be persuaded to follow this example) in order to reduce the risk of blocking by Panasonic. As you implied, 8640 API calls per home may be seen as excessive compared to what they had envisaged.

Coming from an IoT background, the level of transactions in the cloud has a big impact on cost, especially when it's free to end-users.

@embee8 Yes, caching the device status was what I was thinking. Now we have HomeBridge working here, we simply don't use the IR remotes any more (and, rarely, the app).

> The text field for string inputs is single-line. Most likely too small to use it productively for release notes

While it's not ideal, I think I could live with this. A single line might be 'Enhancements to xyz. Please see release notes for details' or 'Fix for changes to Panasonic ComfortCloud API'. It means people would see at a glance what had changed within their Homebridge environment without going to Github (which I suspect some users no little about).

Point taken about going OT for this last point!

**Comment by mkz212** [comment]
@embee8 @jandersonhill 

Public release:
- get version and changelog from latest github release (with latest tag)

Beta release:
- get changelog and version from latest release (with tag pre-release)
- it will be one changelog for all betas with the same version, e.g. in github will be 1.9.0 pre release , and versions will be 1.9.0-beta.0 , 1.9.0-beta.1, 1.9.0-beta.2 etc. (auto increment)

**Comment by mkz212** [comment]
@embee8 

Such a workflow could be added. To close the old Issues. 

https://github.com/hjdhjd/homebridge-unifi-protect/actions/runs/7232660548/workflow
